- hosts: nfs-server
  become: yes
  tasks:        
        
    - name: Create dir 
      file:
        path: "{{ mount_path }}"
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: 777 

        
    - name: Copy exports file.
      template:
        src: ./exports.j2
        dest: /etc/exports
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: 0644
                
    - name: NFS apply change configrue
      shell: systemctl reload nfs;exportfs -a
      
    - set_fact:
        data: 
         mount_path: "{{ mount_path }}"
