- hosts: all
  become: yes
  tasks:        
        
    - name: Create dir 
      file:
        path: /mnt/kubedata/
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: 777 

        
    - name: Add a line exports
      lineinfile:
        path: /etc/exports
        line: "/mnt/kubedata/ * (rw,sync,no_subtree_check,no_root_squash,no_all_squash,insecure)"
#       with_itmes: "{{ node_ips }}"
                
    - name: exportfs
      shell: exportfs -rav
