- hosts: nfs-server
  become: yes
  tasks:
    - name: Get the public IP address of the network.
      uri:
        url: https://api.ipify.org?format=json
        method: Get
      changed_when: false
      register: public_ip
      until: public_ip.status == 200
      retries: 10
      delay: 5 
      
     
    - file:
        path: /tmp/nfs
        state: directory
      
    - name: Mount NFS
      mount:
        src: "{{public_ip['json']['ip']}}:{{ mount_path }}"
        path: /tmp/nfs
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs
        
    - name: Unmounted NFS
      mount:
        path: /tmp/nfs
        state: unmounted
        fstype: nfs
        
    - set_stats:
        data: 
          nfs: 
            server: "{{public_ip['json']['ip']}}:{{ mount_path }}"
          
